# Generated by Django 6.0.3 on 2026-03-23 06:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('core', '0002_alter_category_options_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': '采购订单', 'verbose_name_plural': '采购订单'},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'verbose_name': '销售订单', 'verbose_name_plural': '销售订单'},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='operator',
            field=models.CharField(default='Weaver', max_length=50, verbose_name='操作员'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='已付金额'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('ORDERED', '已下单'), ('RECEIVED', '已全部入库'), ('PARTIAL', '部分入库'), ('CANCELLED', '已取消')], default='ORDERED', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='总金额'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际发货时间'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='special_needs',
            field=models.CharField(blank=True, max_length=200, verbose_name='特殊要求'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('SHIPPING', '发货记录'), ('RETURN', '退货处理'), ('REPRODUCE', '重新生产'), ('QUALITY', '质检反馈'), ('REMARK', '普通备注')], max_length=20, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='partner',
            field=models.ForeignKey(limit_choices_to=models.Q(('partner_type', 'SUPPLIER'), ('partner_type', 'BOTH'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='core.partner', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='partner',
            field=models.ForeignKey(limit_choices_to=models.Q(('partner_type', 'CUSTOMER'), ('partner_type', 'BOTH'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='core.partner', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tracking_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='快递单号/装车号'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='custom_product_name',
            field=models.CharField(help_text='给客户看的自定义名称', max_length=200, verbose_name='客户侧产品名'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='关联后可支持自动扣减库存', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='内部关联物料'),
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='正数为收款/调增，负数为付款/调减', max_digits=15, verbose_name='变动金额')),
                ('trx_type', models.CharField(choices=[('COLLECT', '收款'), ('PAY', '付款'), ('ADJUST', '调账')], max_length=20, verbose_name='交易类型')),
                ('note', models.TextField(blank=True, verbose_name='详情说明/扣款原因')),
                ('operator', models.CharField(max_length=50, verbose_name='操作员')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partner', verbose_name='关联单位')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.purchaseorder')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='采购物料')),
            ],
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_quantity', models.DecimalField(decimal_places=2, help_text='增加为正，减少为负', max_digits=12, verbose_name='变动数量')),
                ('log_type', models.CharField(choices=[('PURCHASE', '采购入库'), ('SALE', '销售出库'), ('PRODUCE', '生产入库'), ('CONSUME', '生产消耗'), ('ADJUST', '盘点调整')], max_length=20, verbose_name='变动类型')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='关联单号或说明')),
                ('operator', models.CharField(max_length=50, verbose_name='操作员')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
