# Generated by Django 6.0.3 on 2026-03-23 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_purchaseorder_options_alter_salesorder_options_and_more'),
        ('core', '0002_alter_category_options_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='financialtransaction',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='financialtransaction',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='financialtransaction',
            name='sales_order',
        ),
        migrations.RemoveField(
            model_name='financialtransaction',
            name='trx_type',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='shipping_at',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='tracking_no',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='special_needs',
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='变动金额'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='note',
            field=models.TextField(blank=True, verbose_name='流水备注'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partner'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('SHIPPING', '发货记录'), ('RETURN', '退货/异常'), ('REMARK', '普通备注')], max_length=20, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/', verbose_name='拍照留底'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('ORDERED', '已下单'), ('PARTIAL', '部分入库'), ('RECEIVED', '全部入库')], default='ORDERED', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='订单总量'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='operator',
            field=models.CharField(max_length=50, verbose_name='录单员'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('ORDERED', '已下单'), ('PRODUCING', '生产中'), ('SHIPPED', '已发货'), ('COMPLETED', '已完成'), ('PENDING', '待处理(异常)')], default='ORDERED', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='custom_product_name',
            field=models.CharField(help_text='给客户看的名称', max_length=200, verbose_name='客户侧产品名'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='内部关联物料'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='订单总量'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='change_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='变动数量'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='log_type',
            field=models.CharField(choices=[('PURCHASE', '采购入库'), ('SALE', '销售出库'), ('PRODUCE', '生产入库'), ('ADJUST', '手动调整')], max_length=20, verbose_name='变动类型'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='关联说明'),
        ),
        migrations.CreateModel(
            name='ReceivingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='本次实收数量')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='收货时间')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='批次备注')),
                ('operator', models.CharField(max_length=50, verbose_name='仓管员')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='business.purchaseorderitem')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_shipped', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='本次实发数量')),
                ('tracking_no', models.CharField(blank=True, max_length=100, verbose_name='物流单号/装车号')),
                ('shipped_at', models.DateTimeField(auto_now_add=True, verbose_name='发货时间')),
                ('operator', models.CharField(max_length=50, verbose_name='发货员')),
                ('sales_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippings', to='business.salesorderitem')),
            ],
        ),
    ]
