# Generated by Django 6.0.3 on 2026-03-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': '采购订单', 'verbose_name_plural': '采购订单'},
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='operator',
            field=models.CharField(default='Weaver', max_length=50, verbose_name='操作员'),
            preserve_default=False,
        ),
    ]
