# Generated by Django 6.0.3 on 2026-03-24 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_purchaseorder_paid_amount'),
        ('core', '0002_alter_category_options_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='detail_description',
            field=models.TextField(blank=True, help_text='记录线长、定标等细节', verbose_name='细节描述'),
        ),
        migrations.CreateModel(
            name='CustomerPreferredProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='常用型号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(limit_choices_to=models.Q(('partner_type', 'CUSTOMER'), ('partner_type', 'BOTH'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='preferred_products', to='core.partner', verbose_name='客户')),
            ],
            options={
                'verbose_name': '客户常用型号',
                'verbose_name_plural': '客户常用型号',
                'ordering': ['-created_at'],
                'unique_together': {('partner', 'name')},
            },
        ),
    ]
