# Generated by Django 6.0.3 on 2026-03-25 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_salesorderitem_detail_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('RECEIVING', '收货记录'), ('RETURN', '退货/异常'), ('REMARK', '普通备注')], max_length=20, verbose_name='事件类型')),
                ('content', models.TextField(verbose_name='详细描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='purchase-events/%Y/%m/', verbose_name='拍照留底')),
                ('operator', models.CharField(max_length=50, verbose_name='操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='business.purchaseorder')),
            ],
        ),
    ]
