# Generated by Django 6.0.3 on 2026-03-25 06:00

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


def seed_opening_balances(apps, schema_editor):
    Partner = apps.get_model('core', 'Partner')
    Ledger = apps.get_model('business', 'PartnerLedgerEntry')

    for partner in Partner.objects.all():
        balance = Decimal(partner.balance or 0)
        if not balance:
            continue
        Ledger.objects.create(
            partner=partner,
            entry_type='OPENING',
            amount=balance,
            note='期初余额',
        )
        partner.balance = balance
        partner.save(update_fields=['balance'])


def remove_opening_balances(apps, schema_editor):
    Ledger = apps.get_model('business', 'PartnerLedgerEntry')
    Ledger.objects.filter(entry_type='OPENING').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_purchaseorderevent'),
        ('core', '0002_alter_category_options_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('SALES', '销售订单'), ('PURCHASE', '采购订单'), ('FINANCE', '财务流水'), ('ADJUST', '余额调整'), ('OPENING', '期初余额')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.partner')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.purchaseorder')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.salesorder')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entry', to='business.financialtransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_opening_balances, remove_opening_balances),
    ]
