# Generated by Django 6.0.3 on 2026-03-26 06:14

from decimal import Decimal

from django.db import migrations, models


def populate_transaction_types(apps, schema_editor):
    FinancialTransaction = apps.get_model('business', 'FinancialTransaction')
    for txn in FinancialTransaction.objects.all():
        amount = Decimal(txn.amount or 0)
        if amount > 0:
            txn.transaction_type = 'RECEIPT'
            txn.amount = -abs(amount)
        elif amount < 0:
            txn.transaction_type = 'PAYMENT'
            txn.amount = -abs(amount)
        else:
            txn.transaction_type = 'ADJUST'
            txn.amount = Decimal('0')
        txn.save(update_fields=['transaction_type', 'amount'])


def reset_transaction_types(apps, schema_editor):
    FinancialTransaction = apps.get_model('business', 'FinancialTransaction')
    FinancialTransaction.objects.update(transaction_type='RECEIPT')


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_partnerledgerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('RECEIPT', '收款'), ('PAYMENT', '付款'), ('ADJUST', '调整')], default='RECEIPT', max_length=20, verbose_name='流水类型'),
        ),
        migrations.RunPython(populate_transaction_types, reset_transaction_types),
    ]
