# Generated by Django 6.0.3 on 2026-03-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_partnerledgerentry_credit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('ORDERED', '已下单'), ('PRODUCING', '生产中'), ('SHIPPED', '已发货'), ('COMPLETED', '已完成')], default='ORDERED', max_length=20, verbose_name='状态'),
        ),
    ]
