# Generated by Django 6.0.3 on 2026-06-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_order_due_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归档时间'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='archived_by',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='归档操作员'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='已归档'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归档时间'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='archived_by',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='归档操作员'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='已归档'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
