# Generated by Django 6.0.3 on 2026-06-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_purchaseorder_archived_at_purchaseorder_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='partner_order_no',
            field=models.CharField(blank=True, default='', help_text='供应商系统里的单号，可空；导出 PDF 时只显示这个字段', max_length=100, verbose_name='供应商订单号'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='partner_order_no',
            field=models.CharField(blank=True, default='', help_text='客户自家系统里的单号，可空；导出 PDF 时只显示这个字段', max_length=100, verbose_name='客户订单号'),
        ),
    ]
