# Generated by Django 6.0.3 on 2026-03-23 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='单位名称')),
                ('partner_type', models.CharField(choices=[('SUPPLIER', '供应商'), ('CUSTOMER', '客户'), ('BOTH', '双重身份'), ('SELF', '工厂自用')], max_length=20, verbose_name='单位类型')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='往来余额')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('category_type', models.CharField(choices=[('RAW_MATERIAL', '原材料'), ('SELF_MADE', '自产件'), ('FINISHED', '成品')], max_length=20, verbose_name='分类属性')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(help_text='自产件必填，如：2026-SH-SD-BK', max_length=100, unique=True, verbose_name='内部管理编号')),
                ('model_name', models.CharField(max_length=100, verbose_name='规格型号')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/', verbose_name='产品图片')),
                ('unit', models.CharField(default='个', max_length=10, verbose_name='单位')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='当前库存量')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='安全库存预警')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='所属分类')),
            ],
        ),
    ]
