# Generated by Django 6.0.3 on 2026-03-23 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '产品分类', 'verbose_name_plural': '产品分类'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': '合作伙伴', 'verbose_name_plural': '合作伙伴'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品物料', 'verbose_name_plural': '产品物料'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.category', verbose_name='上级分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/', verbose_name='产品展示图'),
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_code',
            field=models.CharField(help_text='自产件编号规则：年份-类别-系列-颜色 (例: 2026-SH-SD-BK)', max_length=100, unique=True, verbose_name='内部管理编号'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='安全库存预警值'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='当前库存'),
        ),
    ]
